Feat s2i admin (#5)
* AB#1284578 - s2i modifica senha inicial por variável de ambiente

* AB#1284578 - informa instance resultante

* AB#1284578 - informa instance resultante

* AB#1284578 - fix tab issue

* AB#1284578 - fix tab issue

diff --git a/backend/.s2i/bin/assemble b/backend/.s2i/bin/assemble
--- a/backend/.s2i/bin/assemble
+++ b/backend/.s2i/bin/assemble
@@ -32,6 +32,26 @@ EOF
     echo "Configuration added to instance.yaml"
 }
 
+
+# Add admin password to instance.yaml
+function add_admin_password() {
+    if [ -z "$ADMIN_PASSWORD" ]; then
+        echo "ERROR: ADMIN_PASSWORD environment variable is not set. Build cannot continue."
+        exit 1
+    fi
+
+    echo "Injecting admin password into instance.yaml"
+    # Replace the value of initial_user_password inside default_context
+    sed -i "s|\(initial_user_password:\s*\).*|\1'${ADMIN_PASSWORD}'|" ./instance.yaml
+
+    # Ensure no tabs in instance.yaml
+    sed -i 's/\t/    /g' ./instance.yaml
+
+
+    echo "Admin password successfully injected into instance.yaml"
+}
+
+
 echo "Default S2I assemble script will begin"
 
 /usr/libexec/s2i/assemble
@@ -64,6 +84,11 @@ if [ $rc -eq 0 ]; then
 	if [ -n "$RELSTORAGE_DSN" ]; then
         add_database_config
     fi
+
+	#replaces initial 1admin passowrd with env var
+	add_admin_password
+	echo "Final instance.yaml:"
+	cat ./instance.yaml
 	
 	echo "Executing make install..."
 	make install
